meta_title: "Trouvez les meilleures dates pour vos billets d'avion"
meta_description: "Dites nous combien de temps vous voulez partir, nous vous trouvons les meilleurs vols"
meta_image: "image.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@nomdevotrecompte" # indispensable pour les Twitter Cards
